### ISSUE TITLE
팀 수정사항 요청

### ISSUE THREAD

**Issue by bboggo** [TaskWeaver/backend#74]
## Todo
- [ ] 팀 전체 조회, 상세 조회 response 통일
- [ ] 팀 전체 조회 시 로그인한 유저도 멤버에 추가
- [ ] 팀 소개 필드 추가

## Due Date
~4/21(일)

## Reference
없습니다.
